//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 16.05.2017 09:25:39
namespace EverywhereServerClientSample.zenon
{
    
    /// <summary>
    /// There are no comments for ZenonDataModel in the schema.
    /// </summary>
    public partial class ZenonDataModel : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ZenonDataModel object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonDataModel(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Everywhere.Service.Data", "EverywhereServerClientSample.zenon");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("EverywhereServerClientSample.zenon", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Everywhere.Service.Data.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for OnlineVariables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonOnlineVariable> OnlineVariables
        {
            get
            {
                if ((this._OnlineVariables == null))
                {
                    this._OnlineVariables = base.CreateQuery<ZenonOnlineVariable>("OnlineVariables");
                }
                return this._OnlineVariables;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonOnlineVariable> _OnlineVariables;
        /// <summary>
        /// There are no comments for ArchiveValues in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonArchiveValue> ArchiveValues
        {
            get
            {
                if ((this._ArchiveValues == null))
                {
                    this._ArchiveValues = base.CreateQuery<ZenonArchiveValue>("ArchiveValues");
                }
                return this._ArchiveValues;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonArchiveValue> _ArchiveValues;
        /// <summary>
        /// There are no comments for Archives in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonArchive> Archives
        {
            get
            {
                if ((this._Archives == null))
                {
                    this._Archives = base.CreateQuery<ZenonArchive>("Archives");
                }
                return this._Archives;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonArchive> _Archives;
        /// <summary>
        /// There are no comments for CEL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonEvent> CEL
        {
            get
            {
                if ((this._CEL == null))
                {
                    this._CEL = base.CreateQuery<ZenonEvent>("CEL");
                }
                return this._CEL;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonEvent> _CEL;
        /// <summary>
        /// There are no comments for Alarms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonAlarm> Alarms
        {
            get
            {
                if ((this._Alarms == null))
                {
                    this._Alarms = base.CreateQuery<ZenonAlarm>("Alarms");
                }
                return this._Alarms;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonAlarm> _Alarms;
        /// <summary>
        /// There are no comments for Variables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonVariable> Variables
        {
            get
            {
                if ((this._Variables == null))
                {
                    this._Variables = base.CreateQuery<ZenonVariable>("Variables");
                }
                return this._Variables;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonVariable> _Variables;
        /// <summary>
        /// There are no comments for AlarmClasses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonAlarmClass> AlarmClasses
        {
            get
            {
                if ((this._AlarmClasses == null))
                {
                    this._AlarmClasses = base.CreateQuery<ZenonAlarmClass>("AlarmClasses");
                }
                return this._AlarmClasses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonAlarmClass> _AlarmClasses;
        /// <summary>
        /// There are no comments for AlarmGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonAlarmGroup> AlarmGroups
        {
            get
            {
                if ((this._AlarmGroups == null))
                {
                    this._AlarmGroups = base.CreateQuery<ZenonAlarmGroup>("AlarmGroups");
                }
                return this._AlarmGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonAlarmGroup> _AlarmGroups;
        /// <summary>
        /// There are no comments for EquipmentGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonEquipmentGroup> EquipmentGroups
        {
            get
            {
                if ((this._EquipmentGroups == null))
                {
                    this._EquipmentGroups = base.CreateQuery<ZenonEquipmentGroup>("EquipmentGroups");
                }
                return this._EquipmentGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonEquipmentGroup> _EquipmentGroups;
        /// <summary>
        /// There are no comments for EquipmentModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ZenonEquipmentModel> EquipmentModels
        {
            get
            {
                if ((this._EquipmentModels == null))
                {
                    this._EquipmentModels = base.CreateQuery<ZenonEquipmentModel>("EquipmentModels");
                }
                return this._EquipmentModels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ZenonEquipmentModel> _EquipmentModels;
        /// <summary>
        /// There are no comments for OnlineVariables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOnlineVariables(ZenonOnlineVariable zenonOnlineVariable)
        {
            base.AddObject("OnlineVariables", zenonOnlineVariable);
        }
        /// <summary>
        /// There are no comments for ArchiveValues in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToArchiveValues(ZenonArchiveValue zenonArchiveValue)
        {
            base.AddObject("ArchiveValues", zenonArchiveValue);
        }
        /// <summary>
        /// There are no comments for Archives in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToArchives(ZenonArchive zenonArchive)
        {
            base.AddObject("Archives", zenonArchive);
        }
        /// <summary>
        /// There are no comments for CEL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCEL(ZenonEvent zenonEvent)
        {
            base.AddObject("CEL", zenonEvent);
        }
        /// <summary>
        /// There are no comments for Alarms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAlarms(ZenonAlarm zenonAlarm)
        {
            base.AddObject("Alarms", zenonAlarm);
        }
        /// <summary>
        /// There are no comments for Variables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVariables(ZenonVariable zenonVariable)
        {
            base.AddObject("Variables", zenonVariable);
        }
        /// <summary>
        /// There are no comments for AlarmClasses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAlarmClasses(ZenonAlarmClass zenonAlarmClass)
        {
            base.AddObject("AlarmClasses", zenonAlarmClass);
        }
        /// <summary>
        /// There are no comments for AlarmGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAlarmGroups(ZenonAlarmGroup zenonAlarmGroup)
        {
            base.AddObject("AlarmGroups", zenonAlarmGroup);
        }
        /// <summary>
        /// There are no comments for EquipmentGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEquipmentGroups(ZenonEquipmentGroup zenonEquipmentGroup)
        {
            base.AddObject("EquipmentGroups", zenonEquipmentGroup);
        }
        /// <summary>
        /// There are no comments for EquipmentModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEquipmentModels(ZenonEquipmentModel zenonEquipmentModel)
        {
            base.AddObject("EquipmentModels", zenonEquipmentModel);
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonOnlineVariable in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("OnlineVariables")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ZenonOnlineVariable : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonOnlineVariable object.
        /// </summary>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="cookie">Initial value of Cookie.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonOnlineVariable CreateZenonOnlineVariable(long status, long timestamp, int cookie, int ID)
        {
            ZenonOnlineVariable zenonOnlineVariable = new ZenonOnlineVariable();
            zenonOnlineVariable.Status = status;
            zenonOnlineVariable.Timestamp = timestamp;
            zenonOnlineVariable.Cookie = cookie;
            zenonOnlineVariable.Id = ID;
            return zenonOnlineVariable;
        }
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Status;
        partial void OnStatusChanging(long value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Timestamp;
        partial void OnTimestampChanging(long value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Cookie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Cookie
        {
            get
            {
                return this._Cookie;
            }
            set
            {
                this.OnCookieChanging(value);
                this._Cookie = value;
                this.OnCookieChanged();
                this.OnPropertyChanged("Cookie");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Cookie;
        partial void OnCookieChanging(int value);
        partial void OnCookieChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Variable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonVariable Variable
        {
            get
            {
                return this._Variable;
            }
            set
            {
                this._Variable = value;
                this.OnPropertyChanged("Variable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonVariable _Variable;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonArchiveValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ArchiveId
    /// Timestamp
    /// Type
    /// VariableId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ArchiveValues")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ArchiveId", "Timestamp", "Type", "VariableId")]
    public partial class ZenonArchiveValue : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonArchiveValue object.
        /// </summary>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="variableId">Initial value of VariableId.</param>
        /// <param name="archiveId">Initial value of ArchiveId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonArchiveValue CreateZenonArchiveValue(int type, long status, long timestamp, int variableId, string archiveId)
        {
            ZenonArchiveValue zenonArchiveValue = new ZenonArchiveValue();
            zenonArchiveValue.Type = type;
            zenonArchiveValue.Status = status;
            zenonArchiveValue.Timestamp = timestamp;
            zenonArchiveValue.VariableId = variableId;
            zenonArchiveValue.ArchiveId = archiveId;
            return zenonArchiveValue;
        }
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Status;
        partial void OnStatusChanging(long value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Timestamp;
        partial void OnTimestampChanging(long value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property VariableName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VariableName
        {
            get
            {
                return this._VariableName;
            }
            set
            {
                this.OnVariableNameChanging(value);
                this._VariableName = value;
                this.OnVariableNameChanged();
                this.OnPropertyChanged("VariableName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VariableName;
        partial void OnVariableNameChanging(string value);
        partial void OnVariableNameChanged();
        /// <summary>
        /// There are no comments for Property VariableId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int VariableId
        {
            get
            {
                return this._VariableId;
            }
            set
            {
                this.OnVariableIdChanging(value);
                this._VariableId = value;
                this.OnVariableIdChanged();
                this.OnPropertyChanged("VariableId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _VariableId;
        partial void OnVariableIdChanging(int value);
        partial void OnVariableIdChanged();
        /// <summary>
        /// There are no comments for Property ArchiveId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ArchiveId
        {
            get
            {
                return this._ArchiveId;
            }
            set
            {
                this.OnArchiveIdChanging(value);
                this._ArchiveId = value;
                this.OnArchiveIdChanged();
                this.OnPropertyChanged("ArchiveId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ArchiveId;
        partial void OnArchiveIdChanging(string value);
        partial void OnArchiveIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonArchive in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Archives")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ZenonArchive : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonArchive object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonArchive CreateZenonArchive(string ID)
        {
            ZenonArchive zenonArchive = new ZenonArchive();
            zenonArchive.Id = ID;
            return zenonArchive;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Values in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ZenonArchiveValue> Values
        {
            get
            {
                return this._Values;
            }
            set
            {
                this._Values = value;
                this.OnPropertyChanged("Values");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ZenonArchiveValue> _Values = new global::System.Data.Services.Client.DataServiceCollection<ZenonArchiveValue>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonEvent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// TimeReceived
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CEL")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "TimeReceived")]
    public partial class ZenonEvent : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonEvent object.
        /// </summary>
        /// <param name="variableStatus">Initial value of VariableStatus.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="timeReceived">Initial value of TimeReceived.</param>
        /// <param name="cookie">Initial value of Cookie.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonEvent CreateZenonEvent(long variableStatus, double value, long timeReceived, int cookie, int ID)
        {
            ZenonEvent zenonEvent = new ZenonEvent();
            zenonEvent.VariableStatus = variableStatus;
            zenonEvent.Value = value;
            zenonEvent.TimeReceived = timeReceived;
            zenonEvent.Cookie = cookie;
            zenonEvent.Id = ID;
            return zenonEvent;
        }
        /// <summary>
        /// There are no comments for Property VariableStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long VariableStatus
        {
            get
            {
                return this._VariableStatus;
            }
            set
            {
                this.OnVariableStatusChanging(value);
                this._VariableStatus = value;
                this.OnVariableStatusChanged();
                this.OnPropertyChanged("VariableStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _VariableStatus;
        partial void OnVariableStatusChanging(long value);
        partial void OnVariableStatusChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Value;
        partial void OnValueChanging(double value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property TimeReceived in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long TimeReceived
        {
            get
            {
                return this._TimeReceived;
            }
            set
            {
                this.OnTimeReceivedChanging(value);
                this._TimeReceived = value;
                this.OnTimeReceivedChanged();
                this.OnPropertyChanged("TimeReceived");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _TimeReceived;
        partial void OnTimeReceivedChanging(long value);
        partial void OnTimeReceivedChanged();
        /// <summary>
        /// There are no comments for Property ComputerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ComputerName
        {
            get
            {
                return this._ComputerName;
            }
            set
            {
                this.OnComputerNameChanging(value);
                this._ComputerName = value;
                this.OnComputerNameChanged();
                this.OnPropertyChanged("ComputerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ComputerName;
        partial void OnComputerNameChanging(string value);
        partial void OnComputerNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this._Text = value;
                this.OnTextChanged();
                this.OnPropertyChanged("Text");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for Property Cookie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Cookie
        {
            get
            {
                return this._Cookie;
            }
            set
            {
                this.OnCookieChanging(value);
                this._Cookie = value;
                this.OnCookieChanged();
                this.OnPropertyChanged("Cookie");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Cookie;
        partial void OnCookieChanging(int value);
        partial void OnCookieChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for AlarmClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonAlarmClass AlarmClass
        {
            get
            {
                return this._AlarmClass;
            }
            set
            {
                this._AlarmClass = value;
                this.OnPropertyChanged("AlarmClass");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonAlarmClass _AlarmClass;
        /// <summary>
        /// There are no comments for AlarmGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonAlarmGroup AlarmGroup
        {
            get
            {
                return this._AlarmGroup;
            }
            set
            {
                this._AlarmGroup = value;
                this.OnPropertyChanged("AlarmGroup");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonAlarmGroup _AlarmGroup;
        /// <summary>
        /// There are no comments for Variable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonVariable Variable
        {
            get
            {
                return this._Variable;
            }
            set
            {
                this._Variable = value;
                this.OnPropertyChanged("Variable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonVariable _Variable;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonAlarm in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// TimeReceived
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Alarms")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "TimeReceived")]
    public partial class ZenonAlarm : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonAlarm object.
        /// </summary>
        /// <param name="deleted">Initial value of Deleted.</param>
        /// <param name="acknowledged">Initial value of Acknowledged.</param>
        /// <param name="variableStatus">Initial value of VariableStatus.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="reactivateNumber">Initial value of ReactivateNumber.</param>
        /// <param name="reactivateStatus">Initial value of ReactivateStatus.</param>
        /// <param name="reactivateTime">Initial value of ReactivateTime.</param>
        /// <param name="timeAcknowledged">Initial value of TimeAcknowledged.</param>
        /// <param name="timeCleared">Initial value of TimeCleared.</param>
        /// <param name="timeReceived">Initial value of TimeReceived.</param>
        /// <param name="alarmStatus">Initial value of AlarmStatus.</param>
        /// <param name="cookie">Initial value of Cookie.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonAlarm CreateZenonAlarm(bool deleted, bool acknowledged, long variableStatus, double value, int reactivateNumber, long reactivateStatus, long reactivateTime, long timeAcknowledged, long timeCleared, long timeReceived, long alarmStatus, int cookie, int ID)
        {
            ZenonAlarm zenonAlarm = new ZenonAlarm();
            zenonAlarm.Deleted = deleted;
            zenonAlarm.Acknowledged = acknowledged;
            zenonAlarm.VariableStatus = variableStatus;
            zenonAlarm.Value = value;
            zenonAlarm.ReactivateNumber = reactivateNumber;
            zenonAlarm.ReactivateStatus = reactivateStatus;
            zenonAlarm.ReactivateTime = reactivateTime;
            zenonAlarm.TimeAcknowledged = timeAcknowledged;
            zenonAlarm.TimeCleared = timeCleared;
            zenonAlarm.TimeReceived = timeReceived;
            zenonAlarm.AlarmStatus = alarmStatus;
            zenonAlarm.Cookie = cookie;
            zenonAlarm.Id = ID;
            return zenonAlarm;
        }
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Deleted;
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for Property Acknowledged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Acknowledged
        {
            get
            {
                return this._Acknowledged;
            }
            set
            {
                this.OnAcknowledgedChanging(value);
                this._Acknowledged = value;
                this.OnAcknowledgedChanged();
                this.OnPropertyChanged("Acknowledged");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Acknowledged;
        partial void OnAcknowledgedChanging(bool value);
        partial void OnAcknowledgedChanged();
        /// <summary>
        /// There are no comments for Property VariableStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long VariableStatus
        {
            get
            {
                return this._VariableStatus;
            }
            set
            {
                this.OnVariableStatusChanging(value);
                this._VariableStatus = value;
                this.OnVariableStatusChanged();
                this.OnPropertyChanged("VariableStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _VariableStatus;
        partial void OnVariableStatusChanging(long value);
        partial void OnVariableStatusChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Value;
        partial void OnValueChanging(double value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property ReactivateNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ReactivateNumber
        {
            get
            {
                return this._ReactivateNumber;
            }
            set
            {
                this.OnReactivateNumberChanging(value);
                this._ReactivateNumber = value;
                this.OnReactivateNumberChanged();
                this.OnPropertyChanged("ReactivateNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ReactivateNumber;
        partial void OnReactivateNumberChanging(int value);
        partial void OnReactivateNumberChanged();
        /// <summary>
        /// There are no comments for Property ReactivateStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ReactivateStatus
        {
            get
            {
                return this._ReactivateStatus;
            }
            set
            {
                this.OnReactivateStatusChanging(value);
                this._ReactivateStatus = value;
                this.OnReactivateStatusChanged();
                this.OnPropertyChanged("ReactivateStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ReactivateStatus;
        partial void OnReactivateStatusChanging(long value);
        partial void OnReactivateStatusChanged();
        /// <summary>
        /// There are no comments for Property ReactivateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ReactivateTime
        {
            get
            {
                return this._ReactivateTime;
            }
            set
            {
                this.OnReactivateTimeChanging(value);
                this._ReactivateTime = value;
                this.OnReactivateTimeChanged();
                this.OnPropertyChanged("ReactivateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ReactivateTime;
        partial void OnReactivateTimeChanging(long value);
        partial void OnReactivateTimeChanged();
        /// <summary>
        /// There are no comments for Property TimeAcknowledged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long TimeAcknowledged
        {
            get
            {
                return this._TimeAcknowledged;
            }
            set
            {
                this.OnTimeAcknowledgedChanging(value);
                this._TimeAcknowledged = value;
                this.OnTimeAcknowledgedChanged();
                this.OnPropertyChanged("TimeAcknowledged");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _TimeAcknowledged;
        partial void OnTimeAcknowledgedChanging(long value);
        partial void OnTimeAcknowledgedChanged();
        /// <summary>
        /// There are no comments for Property TimeCleared in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long TimeCleared
        {
            get
            {
                return this._TimeCleared;
            }
            set
            {
                this.OnTimeClearedChanging(value);
                this._TimeCleared = value;
                this.OnTimeClearedChanged();
                this.OnPropertyChanged("TimeCleared");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _TimeCleared;
        partial void OnTimeClearedChanging(long value);
        partial void OnTimeClearedChanged();
        /// <summary>
        /// There are no comments for Property TimeReceived in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long TimeReceived
        {
            get
            {
                return this._TimeReceived;
            }
            set
            {
                this.OnTimeReceivedChanging(value);
                this._TimeReceived = value;
                this.OnTimeReceivedChanged();
                this.OnPropertyChanged("TimeReceived");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _TimeReceived;
        partial void OnTimeReceivedChanging(long value);
        partial void OnTimeReceivedChanged();
        /// <summary>
        /// There are no comments for Property ComputerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ComputerName
        {
            get
            {
                return this._ComputerName;
            }
            set
            {
                this.OnComputerNameChanging(value);
                this._ComputerName = value;
                this.OnComputerNameChanged();
                this.OnPropertyChanged("ComputerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ComputerName;
        partial void OnComputerNameChanging(string value);
        partial void OnComputerNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this._Text = value;
                this.OnTextChanged();
                this.OnPropertyChanged("Text");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for Property AlarmStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AlarmStatus
        {
            get
            {
                return this._AlarmStatus;
            }
            set
            {
                this.OnAlarmStatusChanging(value);
                this._AlarmStatus = value;
                this.OnAlarmStatusChanged();
                this.OnPropertyChanged("AlarmStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AlarmStatus;
        partial void OnAlarmStatusChanging(long value);
        partial void OnAlarmStatusChanged();
        /// <summary>
        /// There are no comments for Property Cookie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Cookie
        {
            get
            {
                return this._Cookie;
            }
            set
            {
                this.OnCookieChanging(value);
                this._Cookie = value;
                this.OnCookieChanged();
                this.OnPropertyChanged("Cookie");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Cookie;
        partial void OnCookieChanging(int value);
        partial void OnCookieChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for AlarmClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonAlarmClass AlarmClass
        {
            get
            {
                return this._AlarmClass;
            }
            set
            {
                this._AlarmClass = value;
                this.OnPropertyChanged("AlarmClass");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonAlarmClass _AlarmClass;
        /// <summary>
        /// There are no comments for AlarmGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonAlarmGroup AlarmGroup
        {
            get
            {
                return this._AlarmGroup;
            }
            set
            {
                this._AlarmGroup = value;
                this.OnPropertyChanged("AlarmGroup");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonAlarmGroup _AlarmGroup;
        /// <summary>
        /// There are no comments for Variable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonVariable Variable
        {
            get
            {
                return this._Variable;
            }
            set
            {
                this._Variable = value;
                this.OnPropertyChanged("Variable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonVariable _Variable;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonVariable in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Variables")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ZenonVariable : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonVariable object.
        /// </summary>
        /// <param name="minimumValue">Initial value of MinimumValue.</param>
        /// <param name="maximumValue">Initial value of MaximumValue.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonVariable CreateZenonVariable(double minimumValue, double maximumValue, int ID)
        {
            ZenonVariable zenonVariable = new ZenonVariable();
            zenonVariable.MinimumValue = minimumValue;
            zenonVariable.MaximumValue = maximumValue;
            zenonVariable.Id = ID;
            return zenonVariable;
        }
        /// <summary>
        /// There are no comments for Property EquipmentGroupGuids in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EquipmentGroupGuids
        {
            get
            {
                return this._EquipmentGroupGuids;
            }
            set
            {
                this.OnEquipmentGroupGuidsChanging(value);
                this._EquipmentGroupGuids = value;
                this.OnEquipmentGroupGuidsChanged();
                this.OnPropertyChanged("EquipmentGroupGuids");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EquipmentGroupGuids;
        partial void OnEquipmentGroupGuidsChanging(string value);
        partial void OnEquipmentGroupGuidsChanged();
        /// <summary>
        /// There are no comments for Property MinimumValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double MinimumValue
        {
            get
            {
                return this._MinimumValue;
            }
            set
            {
                this.OnMinimumValueChanging(value);
                this._MinimumValue = value;
                this.OnMinimumValueChanged();
                this.OnPropertyChanged("MinimumValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _MinimumValue;
        partial void OnMinimumValueChanging(double value);
        partial void OnMinimumValueChanged();
        /// <summary>
        /// There are no comments for Property MaximumValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double MaximumValue
        {
            get
            {
                return this._MaximumValue;
            }
            set
            {
                this.OnMaximumValueChanging(value);
                this._MaximumValue = value;
                this.OnMaximumValueChanged();
                this.OnPropertyChanged("MaximumValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _MaximumValue;
        partial void OnMaximumValueChanging(double value);
        partial void OnMaximumValueChanged();
        /// <summary>
        /// There are no comments for Property Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Unit
        {
            get
            {
                return this._Unit;
            }
            set
            {
                this.OnUnitChanging(value);
                this._Unit = value;
                this.OnUnitChanged();
                this.OnPropertyChanged("Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Unit;
        partial void OnUnitChanging(string value);
        partial void OnUnitChanged();
        /// <summary>
        /// There are no comments for Property ResourcesLabel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResourcesLabel
        {
            get
            {
                return this._ResourcesLabel;
            }
            set
            {
                this.OnResourcesLabelChanging(value);
                this._ResourcesLabel = value;
                this.OnResourcesLabelChanged();
                this.OnPropertyChanged("ResourcesLabel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResourcesLabel;
        partial void OnResourcesLabelChanging(string value);
        partial void OnResourcesLabelChanged();
        /// <summary>
        /// There are no comments for Property Identification in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identification
        {
            get
            {
                return this._Identification;
            }
            set
            {
                this.OnIdentificationChanging(value);
                this._Identification = value;
                this.OnIdentificationChanged();
                this.OnPropertyChanged("Identification");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identification;
        partial void OnIdentificationChanging(string value);
        partial void OnIdentificationChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonAlarmClass in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Number
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AlarmClasses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Number")]
    public partial class ZenonAlarmClass : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonAlarmClass object.
        /// </summary>
        /// <param name="number">Initial value of Number.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonAlarmClass CreateZenonAlarmClass(int number)
        {
            ZenonAlarmClass zenonAlarmClass = new ZenonAlarmClass();
            zenonAlarmClass.Number = number;
            return zenonAlarmClass;
        }
        /// <summary>
        /// There are no comments for Property EquipmentGroupGuids in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EquipmentGroupGuids
        {
            get
            {
                return this._EquipmentGroupGuids;
            }
            set
            {
                this.OnEquipmentGroupGuidsChanging(value);
                this._EquipmentGroupGuids = value;
                this.OnEquipmentGroupGuidsChanged();
                this.OnPropertyChanged("EquipmentGroupGuids");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EquipmentGroupGuids;
        partial void OnEquipmentGroupGuidsChanging(string value);
        partial void OnEquipmentGroupGuidsChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Number;
        partial void OnNumberChanging(int value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonAlarmGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Number
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AlarmGroups")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Number")]
    public partial class ZenonAlarmGroup : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonAlarmGroup object.
        /// </summary>
        /// <param name="number">Initial value of Number.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonAlarmGroup CreateZenonAlarmGroup(int number)
        {
            ZenonAlarmGroup zenonAlarmGroup = new ZenonAlarmGroup();
            zenonAlarmGroup.Number = number;
            return zenonAlarmGroup;
        }
        /// <summary>
        /// There are no comments for Property EquipmentGroupGuids in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EquipmentGroupGuids
        {
            get
            {
                return this._EquipmentGroupGuids;
            }
            set
            {
                this.OnEquipmentGroupGuidsChanging(value);
                this._EquipmentGroupGuids = value;
                this.OnEquipmentGroupGuidsChanged();
                this.OnPropertyChanged("EquipmentGroupGuids");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EquipmentGroupGuids;
        partial void OnEquipmentGroupGuidsChanging(string value);
        partial void OnEquipmentGroupGuidsChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Number;
        partial void OnNumberChanging(int value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonEquipmentGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Guid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EquipmentGroups")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Guid")]
    public partial class ZenonEquipmentGroup : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonEquipmentGroup object.
        /// </summary>
        /// <param name="guid">Initial value of Guid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonEquipmentGroup CreateZenonEquipmentGroup(string guid)
        {
            ZenonEquipmentGroup zenonEquipmentGroup = new ZenonEquipmentGroup();
            zenonEquipmentGroup.Guid = guid;
            return zenonEquipmentGroup;
        }
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("Guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Guid;
        partial void OnGuidChanging(string value);
        partial void OnGuidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Model in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonEquipmentModel Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this._Model = value;
                this.OnPropertyChanged("Model");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonEquipmentModel _Model;
        /// <summary>
        /// There are no comments for ParentGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZenonEquipmentGroup ParentGroup
        {
            get
            {
                return this._ParentGroup;
            }
            set
            {
                this._ParentGroup = value;
                this.OnPropertyChanged("ParentGroup");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ZenonEquipmentGroup _ParentGroup;
        /// <summary>
        /// There are no comments for ChildGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ZenonEquipmentGroup> ChildGroups
        {
            get
            {
                return this._ChildGroups;
            }
            set
            {
                this._ChildGroups = value;
                this.OnPropertyChanged("ChildGroups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ZenonEquipmentGroup> _ChildGroups = new global::System.Data.Services.Client.DataServiceCollection<ZenonEquipmentGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Everywhere.Service.Data.ZenonEquipmentModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Guid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EquipmentModels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Guid")]
    public partial class ZenonEquipmentModel : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ZenonEquipmentModel object.
        /// </summary>
        /// <param name="guid">Initial value of Guid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ZenonEquipmentModel CreateZenonEquipmentModel(string guid)
        {
            ZenonEquipmentModel zenonEquipmentModel = new ZenonEquipmentModel();
            zenonEquipmentModel.Guid = guid;
            return zenonEquipmentModel;
        }
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("Guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Guid;
        partial void OnGuidChanging(string value);
        partial void OnGuidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for EquipmentGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ZenonEquipmentGroup> EquipmentGroups
        {
            get
            {
                return this._EquipmentGroups;
            }
            set
            {
                this._EquipmentGroups = value;
                this.OnPropertyChanged("EquipmentGroups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ZenonEquipmentGroup> _EquipmentGroups = new global::System.Data.Services.Client.DataServiceCollection<ZenonEquipmentGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
